name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-frontend:latest -f Dockerfile.frontend .

    - name: Push to DockerHub
      run: docker push my-frontend:latest

    - name: Deploy to Server
      run: |
        ssh user@server "docker pull my-frontend:latest && docker run -d -p 80:80 my-frontend:latest"
